print('Ola, seja bem vindo ao calculo de IMC')
peso = (float(input('digite o peso em kilos: ')))
altura = (float(input('digite sua altura em metros: ')))
imc = (peso/(altura*altura))
print  (f'o seu calculo IMC é de: {imc:.2f} ')